### PR TITLE
Extensible cache driver framework

### PR DESCRIPTION
**Pull request by AndrewJo**
This PR adds ability for users to extend **adonis-throttle** by providing custom cache drivers. Redis driver is included as a reference implementation. This PR should not break any backwards-compatibility and the minor version can be bumped as per SEMVER 2.0 specification.

## Changes

- [x] Introduce `Adonis/Addons/Throttle/Cache` abstract base class to ensure public API methods used by `Adonis/Addons/Throttle` class are implemented by the user
- [x] Refactor `./src/Drivers/Cache/Memory` class to extend `Cache` abstract base class
- [x] Include `./src/Drivers/Cache/Redis` class as reference implementation
  - Recommended for use in clustered, containerized or serverless environments where state must be shared across multiple instances of AdonisJs framework running on different machines
  - **adonis-throttle** does not include `@adonisjs/redis` as dependency to keep dependency tree small. The end-user is responsible for installing `@adonisjs/redis` as dependency in their project should they wish to use the Redis driver
- [x] Add `instructions` CLI hook (`instructions.js`, `instructions.md`)
  - When installed via `adonis install` CLI command, automatically adds `config/throttle.js` to user's project and displays usage instructions
- [x] Update README with new installation instructions, and adds new section for extending cache drivers

### CODE REVIEW

**Comment by masasron** [comment]
Thank you @AndrewJo, great work! 👍

**Comment by AndrewJo** [comment]
> Thank you @AndrewJo, great work! 👍

You're welcome @masasron! I decided to write it after I realized that this provider doesn't consistently rate limit requests if I horizontally scale AdonisJs in Docker containers. 

Please let me know when you plan on releasing v2.2.0 on npm.

Also, what are your plans for CI/CD for this package? I can help set up an automated release pipeline so that a new version tag would trigger a new npm release if you're interested.

**Comment by masasron** [comment]
@AndrewJo that would be great, let's talk

**Comment by AndrewJo** [comment]
@masasron sounds good. I'll create a new issue. Let's move our conversation there.

**Pull request merged**
